config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new]  
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_create :update_comments_counter

  def update_comments_counter
    post_id = post.id
    Post.increment_counter(:comments_counter, post_id)
  end
end

app/models/comments.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_create :update_comments_counter

  private

  def update_comments_counter
    post_id = post.id
    Post.increment_counter(:comments_counter, post_id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_create :update_likes_counter

  def update_likes_counter
    post_id = post.id
    Post.increment_counter(:likes_counter, post_id)
  end
end

app/models/likes.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_create :update_likes_counter

  private

  def update_likes_counter
    post_id = post.id
    Post.increment_counter(:likes_counter, post_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_create :posts_counter_update
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end

  def posts_counter_update
    author_id = author.id
    User.increment_counter(:posts_counter, author_id)
  end
end

app/models/posts.rb
class Post < ApplicationRecord
  after_create :posts_counter_update
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  def recent_comments(id)
    Comments.where(post_id: id).order(created_at: :desc).limit(5)
  end

  private

  def posts_counter_update
    author_id = author.id
    User.increment_counter(:posts_counter, author_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :comments, through: :posts
  has_many :likes, through: :posts

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    Post.where(author_id: id).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio email password confirm_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comments = Comment.new
  end

  def create
    new_comment = Comment.new(text: params[:comment][:text], post: Post.find(params[:post_id]), author: current_user)
    if new_comment.save
      redirect_to user_posts_path
    else
      render :new
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    post = Post.find(params[:post_id])
    author = User.find(params[:user_id])
    like = Like.new(author:, post:)

    return unless like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.where(id: params[:user_id]).first
    @posts = Post.includes(:comments).where(author_id: params[:user_id])
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.all
    @user = User.find(params[:user_id])
    @all_users = User.all
  end

  def create
    new_post = Post.new(title: params[:post][:title], text: params[:post][:text], author: current_user)
    if new_post.save
      redirect_to user_posts_path
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(author_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add a comment</h1>

<%= form_with model: @comments, url: user_post_comments_path do |f| %>
    <div>
        <%= f.label :Text %>
        <%= f.text_field :text %>
    </div>
    <br>

    <%= f.submit "Add comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_card.html.erb
<div class="posts_index_post_and_comment_container">
    <div class="posts_index_user_posts_container">
        <a href="/users/<%=user.id%>/posts/<%=post.id%>">
            <h3 class="posts_index_user_post_title"><%=post.title%></h3>
        </a>
        <p><%=post.text%></p>      
        <p class="posts_index_user_post_stats">
            <%= "Comments: #{post.comments_counter}, Likes: #{post.likes_counter}"%>
        </p>
    </div>
    <div class="posts_index_user_comments_container">   
        <%="No comments for this post yet" if post.comments_counter == 0%>
        <%post.recent_comments.each do |comment|%>
            <%if comment.post_id == post.id%>
                <%if comment.author_id == user.id%>
                    <%= "#{user.name}: #{comment.text}"%> <br/>
                <%end%>
            <%end%>
        <%end%>
    </div>
</div>

app/views/posts/index.html.erb

<div class="posts_index_user">
    <div class="posts_index_user_image">
        <img src=<%=@user.photo%>>
    </div>
    <div class="posts_index_user_details">

        <h3 class="posts_index_user_details_username"><%=@user.name%></h3>
        <p class="posts_index_user_details_number_of_posts">Number of posts: <%=@user.posts_counter%></p>
    </div>
</div>

<div class="posts_index_user_posts">
    <%@posts.each do |post|%>
    
        <%= render partial: "post_card", locals: {post: post, comments: post.comments, user: @user}%>

    <%end%>
</div>
    
<div class="posts_index_pagination_button">
    <a href="/users/<%=@user.id%>/posts/new">    
    <button>
        Add New Post       
    </button>
</div>

app/views/posts/new.html.erb
<h1> Add new post </h1>

<%= form_with model: @post, url: user_posts_path do |f|%>
    <div>
        <%= f.label :Title %><br>
        <%= f.text_field :title %>
    </div>
    <br>

    <div>
        <%= f.label :Text %><br>
        <%= f.text_field :text %>
    </div>
    <br>

    <%= f.submit 'Add post' %><br>
<% end %> 

app/views/posts/show.html.erb
<div class="posts_show_container">

    <div class="posts_show_post_container">
        <p class="posts_show_post_title">
            <%="#{@post.title} by #{@user.name}"%>
        </p>

        <p class="posts_show_post_stats">
            <%="Comments: #{@post.comments_counter}, Likes: #{@post.likes_counter}"%>
        </p>

        <p class="posts_show_post_text">
            <%= @post.text%>
        </p>
    </div>

    <div class="posts_show_comments_container">
        <%="No comments for this post yet" if @post.comments_counter == 0%>
        <%@comments.each do |comment|%>
            <%@all_users.each do |each_user|%>
                <p><%= "#{each_user.name}: #{comment.text}" if each_user.id == comment.author_id && comment.post_id == @post.id%></p>
            <%end%>
        <%end%>
    </div>

    <div class="posts_index_pagination_button">
        <a href="/users/<%=@user.id%>/posts/<%=@post.id%>/comments/new">    
        <button>
            Add New Comment      
        </button>
    </div>

</div>

app/views/users/_post_card.html.erb
<div class="users_show_user_posts_container">
    <h3 class="users_show_user_post_title">
        <%=post.title%>
    </h3>
    <p>
        <%=post.text%>
    </p>
    <p class="users_show_user_post_stats">
        <%= "Comments: #{post.comments_counter}, Likes: #{post.likes_counter}"%>
    </p>
</div>

app/views/users/_user_card.html.erb
<div class="users_index_card">
    <div class="users_index_card_image">
        <img src=<%=user.photo%>>
    </div>
    <div class="users_index_card_details">
        <h3 class="users_index_card_details_username">  
            <a href="/users/<%=user.id%>">
                <%=user.name%>
            </a>
        </h3>
        <p class="users_index_card_details_number_of_posts">
            Number of posts: <%=user.posts_counter%>
        </p>
    </div>
</div>

app/views/users/index.html.erb
<h1>David's blog app</h1>
<% @users.each do |user| %>
    <%= render partial: "user_card", locals: {user: user}%>
<% end %>

app/views/users/show.html.erb
<div class="users_show_user">
    <div class="users_show_user_image">
        <img src=<%=@user.photo%>>
    </div>
    <div class="users_show_user_details">        
        <p class="users_show_user_details_username">
            <%=@user.name%>
        </p>
        <p class="user_show_user_details_number_of_posts">
            Number of posts: <%=@user.posts_counter%>
        </p>
    </div>
</div>
<div class="users_show_user_bio">
    <div class="users_show_user_bio_container">
        <h3 class="users_show_user_bio_label">Bio</h3>
        <p>
            <%=@user.bio%>
        </p>
    </div>
</div>
<div class="users_show_user_posts">
    <% @user.recent_posts.each do |post| %>
        <%= render partial: "post_card", locals: {post: post}%>
    <% end %>
</div>

<div class="users_show_user_all_posts_button_container">
    <a href="/users/<%=@user.id%>/posts">
        <button>
            See all posts        
        </button>
    </a>
</div>